before:
  hooks:
    - go mod tidy

builds:
  # LINUX/WINDOWS AMD64 BUILD WITH CGO
  - id: distroface_amd64
    main: ./cmd/distroface/main.go
    binary: distroface
    env:
      - CGO_ENABLED=1
      # NEED THIS FOR WIN X-COMPILE
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

  # DARWIN AMD64 BUILD WITHOUT CGO
  - id: distroface_darwin_amd64
    main: ./cmd/distroface/main.go
    binary: distroface
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w

  # ARM64 BUILDS WITHOUT CGO
  - id: distroface_arm64
    main: ./cmd/distroface/main.go
    binary: distroface
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: dfcli_darwin
    main: ./cmd/dfcli/main.go
    binary: dfcli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s

  - id: dfcli_win
    main: ./cmd/dfcli/main.go
    binary: dfcli
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w

  - id: dfcli_linux
    main: ./cmd/dfcli/main.go
    binary: dfcli
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s

  - id: dfcli_arm64
    main: ./cmd/dfcli/main.go
    binary: dfcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s

archives:
  - id: distroface
    builds:
      - distroface_amd64
      - distroface_darwin_amd64
      - distroface_arm64
    format: tar.gz
    name_template: "distroface_{{ .Version }}_{{ .Arch }}"
    files:
      - config.yml
      - web/build/**/*
    format_overrides:
      - goos: windows
        format: zip
        
  - id: dfcli
    builds:
      - dfcli_darwin
      - dfcli_linux
      - dfcli_win
    name_template: "dfcli_{{ .Version }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
