before:
  hooks:
    - go mod tidy

builds:
  - id: distroface
    main: ./cmd/distroface/main.go
    binary: distroface
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
    flags:
      - -tags=sqlite_omit_load_extension
    ldflags:
      - -s -w

  - id: distroface_darwin
    main: ./cmd/distroface/main.go
    binary: distroface
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -tags=sqlite_omit_load_extension
    ldflags:
      - -s -w
      
  - id: dfcli
    main: ./cmd/dfcli/main.go
    binary: dfcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: distroface
    builds: [distroface, distroface_darwin]
    format: tar.gz
    name_template: "distroface_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - config.yml
      - web/build/**/*
    format_overrides:
      - goos: windows
        format: zip
        
  - id: dfcli
    builds: [dfcli]
    format: tar.gz
    name_template: "dfcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
