storage:
  root_directory: "~/.distroface/data"

server:
  port: "8668"
  domain: "registry.localdomain"
  rsa_key_file: "~/.distroface/certs/distro_auth.key"
  cert_bundle: "~/.distroface/certs/distro_auth.crt"

database:
  path: "~/.distroface/db/distro.db"

auth:
  realm: "http://registry.localdomain:8668/auth/token"
  service: "registry.localdomain:8668"
  issuer: "registry-auth-server"

init:
  drop: false # SET VIA ENV TO DROP ALL TABLES ON INIT
  roles: true
  groups: true
  user: true
  username: admin
  password: admin
