storage:
  root_directory: "/data/registry"

server:
  port: "8668"
  domain: "0.0.0.0"
  rsa_key_file: "/data/certs/distro_auth.key"
  cert_bundle: "/data/certs/distro_auth.crt"

database:
  path: "/data/db/distro.db"

auth:
  realm: "http://0.0.0.0:8668/auth/token"
  service: "registry:8668"
  issuer: "registry-auth-server"

init:
  drop: false # SET VIA ENV TO DROP ALL TABLES ON INIT
  roles: true
  groups: true
  user: true
  username: $REGISTRY_USER
  password: $REGISTRY_PASS
